services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SkillsRock
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iamroot
  db:
    image: postgres:14
    container_name: user-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=SkillsRock
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 5s
      interval: 5s
      retries: 10
  redis:
    image: redis:8.2.0
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  redis_data: